### ISSUE TITLE
Short username/local-part login

### ISSUE THREAD

**Issue by graphik55** [afterlogic/webmail-lite-8#14] opened 2018-04-25 05:17 UTC
It seems to be impossible to connect to an IMAP server if only the local-part of the E-Mail address is usable as username.
In version 7 there was an option to enable such login: https://afterlogic.com/docs/webmail-lite/configuring-webmail/configuring-login-page 

e.g. 
E-Mail: graphik55@example.com
Login username: graphik55

Is there any solution for this?

**Comment by afterlogic-support** [comment] 2018-04-25 09:10
We have actually implemented a solution for this in WebMail Pro v8:
https://afterlogic.com/webmail-client
Under Mail Servers, there's a setting added "Use full email address as login" for each server.
But for some reason, it looks like the setting isn't there in WebMail Lite v8, I've asked the developers to look into this. Most likely, it's a bug which will be corrected in the next update.

**Comment by graphik55** [comment] 2018-04-25 12:09
Great news and thank you for such a fast reply.

**Comment by afterlogic-support** [comment] 2018-04-25 12:15
Have just uploaded a new package, available at:
https://afterlogic.org/download/webmail-lite-php
Hope it works for you.

**Comment by graphik55** [comment] 2018-04-25 17:24
I am sorry but it is not working properly.
I have multiple issues:

1. If I create a "Mail Server" with unchecked "Use full email address as login", the option is not unchecked. I need to edit the Mail Server and uncheck again.

2. I was able to connect to my Mail Server one time. While try to sync my Mails I got a red notification for wrong username/password.
If I logout from my Mail Server and try to login again it is not possible. I need to clear the database and setup my Mail Server again.

Do you have some ideas?

I attached my debug log from my first login attempt, maybe it is useful. It is anonymized:
Domain: example.com
User: joe
Mail Server: mail.example.com
[webmail.log](https://github.com/afterlogic/webmail-lite-8/files/1948095/webmail.log)

**Comment by afterlogic-support** [comment] 2018-04-26 10:09
Thanks, looks like there's a problem indeed, i was able to reproduce issue #1 and the developers will look into both the issues. Will keep you posted.

**Comment by afterlogic-support** [comment] 2018-04-28 10:47
Developers state they have corrected the issue, the fix will be included in the next package.

**Comment by Pusnow** [comment] 2018-07-27 19:46
When do I get this fix at the Debian repo? (deb http://apt.afterlogic.com/stable /)

**Comment by afterlogic-support** [comment] 2018-07-29 10:05
The package will be updated once version 8.2 is released, ETA is 1-2 weeks from now.

**Comment by afterlogic-support** [comment] 2018-08-24 09:29
The issue should be corrected by now, both in ZIP package and in Debian repository. Should you encounter it within 8.2 release, let us know.

**Closed by afterlogic-support** 2018-08-24 09:29 UTC
