### ISSUE TITLE
"Email account settings: Signature" and "Addressbooks" are not updated by "Save".

### ISSUE THREAD

**Issue by lvarnava** [afterlogic/webmail-lite-8#116] opened 2024-11-17 17:58 UTC
Debian GNU/Linux 12 (bookworm)
PHP 8.2.24
apache2 2.4.62
afterlogic-lite 9.8.0

Hi!

To Reproduce:

I log into my user account.

1. Go to "Settings"
2. "Email account"
3. "Signature"
4. Edit signature
5. Save - "Settings have been updated successfully".
6. Go to "New Message"
7. Open to compose the letter
8. Result - signature is not updated

It updates only after "F5".

The same effect when adding or editing an address book in "Manage address books".

**Comment by afterlogic-support** [comment] 2024-11-18 06:56
Hello,

The issue with signature is a known one, it has already been corrected and the fix will be included in upcoming 9.8.1 release. To fix the issue on your installation, locate the following line in `webmail/static/js/51.app.3a5430b621288859f3a7.js` file:

```javascript
App.broadcastEvent('MailWebclient::ParseAccount::after', { account: this , data: oData });
```

and add the following code before it:

```javascript
ko.computed(function() {
	const sSignature = this.signature()
	const bUseSignature = this.useSignature()
	const sFriendlyName = this.friendlyName()
	const oIdentity = _.find(this.identities(), oIdentity => oIdentity.bAccountPart)
	
	if (oIdentity) {
		oIdentity.signature(sSignature)
		oIdentity.useSignature(bUseSignature)
		oIdentity.friendlyName(sFriendlyName)
	}
}, this)
```

You'll need to set "UseAppMinJs" to **false** in `data/settings/config.json` file so that non-minified JavaScript is used, and purge browser cache to apply changes.

> The same effect when adding or editing an address book in "Manage address books".

This issue, however, wasn't among the known ones. I have reported it to the developers. Thanks.

**Comment by afterlogic-support** [comment] 2024-11-18 07:09
> locate the following line in `webmail/static/js/51.app.3a5430b621288859f3a7.js` file:

In WebMail Lite 9.8.0, the file is `static/js/27.app.a1ff73765e2928b89a52.js` instead.

**Comment by lvarnava** [comment] 2024-11-18 11:56
Thanks. It works.

**Comment by afterlogic-support** [comment] 2024-12-28 07:52
> The same effect when adding or editing an address book in "Manage address books"

We've checked it again using the [Live Demo](https://lite.afterlogic.com/) and we're not able to reproduce the issue, no matter what we try, the book is there in Contacts right after being created.

If you can provide a reliable way of reproducing the issue, please let us know. Thanks!

**Closed by afterlogic-support** 2024-12-28 07:52 UTC
